version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - nah-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - nah-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: nah-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test
