version: 2
jobs:
  build:
    working_directory: ~/rollup-plugin-just-gzip
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - rollup-plugin-just-gzip-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - rollup-plugin-just-gzip-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: rollup-plugin-just-gzip-{{ checksum "package.json" }}
      
      - run: yarn test
      - run: bash <(curl -s https://codecov.io/bash)
